### ISSUE TITLE
Possible Pixi bug with PyTorch resolution

### ISSUE THREAD

**Issue by matthewfeickert** [carpentries-incubator/reproducible-ml-workflows#23]
In

https://github.com/carpentries-incubator/reproducible-ml-workflows/blob/4d5795dc94a980dac8c299518427c4196959659f/episodes/cuda_conda_pacakges.md#L464-L514

this results in

https://github.com/carpentries-incubator/reproducible-ml-workflows/blob/4d5795dc94a980dac8c299518427c4196959659f/episodes/code/cuda-exercise/pixi.toml#L11-L12

That's an extremely old version of PyTorch.

If you change the manifest to first require Python as a dependency, then it able to resolve `pytorch-cpu` to the correct modern versions.

```toml
[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "cuda-exercise"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.0,<3"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
cuda-version = "12.9.*"
pytorch-gpu = ">=2.7.0,<3"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
```

This seems like it might be a bug to me. If not, then I think a package on conda-forge needs to get marked as broken to avoid this.

**Comment by matthewfeickert** [comment]
Interesting. It seems there must be some issue with the `pytorch-cpu` metapackage as

```console
$ pixi init debug && cd debug
$ pixi workspace platform add linux-64
$ pixi add pytorch-cpu
✔ Added pytorch-cpu >=1.6.0,<2
```

gives

```toml
[workspace]
channels = ["conda-forge"]
name = "pytorch-debug"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch-cpu = ">=1.6.0,<2"
```

and the same thing happens for

```console
$ pixi init debug && cd debug
$ pixi workspace platform add linux-64 osx-arm64
$ pixi add pytorch-cpu
✔ Added pytorch-cpu >=1.6.0,<2
```
```toml
[workspace]
channels = ["conda-forge"]
name = "pytorch-debug"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch-cpu = ">=1.6.0,<3"
```

but, if we add Python first then we can get modern PyTorch

```console
$ pixi init debug && cd debug
$ pixi workspace platform add linux-64 osx-arm64
$ pixi add python
✔ Added python >=3.13.5,<3.14
$ pixi add pytorch-cpu
✔ Added pytorch-cpu >=2.7.1,<3
```

```toml
[workspace]
channels = ["conda-forge"]
name = "pytorch-debug"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pytorch-cpu = ">=2.7.1,<3"
```

Unclear why.
